# Generated by Django 3.1.1 on 2020-10-11 20:53

from django.db import migrations, models
import estudiante.models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20200521_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='anno',
            field=models.IntegerField(default=1, validators=[estudiante.models.valid_year], verbose_name='Año'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
